url: https://ssg.rust.code-maven.com
repo: https://github.com/szabgab/code-maven.rs
branch: main
site_name: Code Maven site generator
link_to_source: true
footer: The [Code Maven RS](https://github.com/szabgab/code-maven.rs).
tags:
  title: Tags
  description: Code Maven in Rust
from:
  name: Gabor Szabo
  email: gabor@szabgab.com
archive:
  title: Archive
  description: List of all the articles about the Rust programming language

authors:
  - name: Gabor Szabo
    nickname: szabgab
    picture: szabgab.png

navbar:
  start:
    - path: /
      title: Home
  end:
    - path: /about
      title: About

