url: https://rust.code-maven.com
site_name: Demo
repo: https://github.com/szabgab/rust.code-maven.com
branch: main
link_to_source: false
footer: Demo of [Code Maven RS](https://github.com/szabgab/code-maven.rs) with links.
tags:
  title: Tags
  description: Articles about Foo Bar
archive:
  title: Archive
  description: Archive of this site
# google_analytics: G-BLABLA
from:
  name: Foo Bar
  email: foo@bar.com
authors:
  - name: Foo Bar
    nickname: foobar
    picture: foobar.png

password: Secret
navbar:
  start:
    - path: /
      title: Home
    - path: /tags/
      title: Tags
  end:
    - path: /archive
      title: Archive
    - path: /about
      title: About

