url: https://rust.code-maven.com
repo: https://github.com/szabgab/rust.code-maven.com
branch: main
site_name: Demo
author_name: Gábor Szabó
link_to_source: true
footer: Demo of [Code Maven RS](https://github.com/szabgab/code-maven.rs) with links.
tags:
  title: Tags
  description: Articles about Rust with tags
# google_analytics: ABC
from:
  name: Gabor Szabo
  email: gabor@szabgab.com
archive:
  title: Archive
  description: List of all the articles about the Rust programming language
authors:
  - name: Gabor Szabo
    nickname: szabgab
    picture: szabgab.png
navbar:
  start:
    - path: /
      title: Home
    - path: /tags/
      title: Tags
    - path: /slides/
      title: Slides
  end:
    - path: /archive
      title: Archive
    - path: /about
      title: About

